# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
import sys


def fib(limit):
	first_num = 1
	second_num = 2

	total = 2
	for i in range(limit -2):
		new_num = first_num + second_num
		if new_num > 4000000:
			break
		if new_num % 2 == 0:
			total += new_num
		first_num = second_num
		second_num = new_num
	return total
		

print(fib(int(sys.argv[1])))